version: '3.9'

services:
  db:
    container_name: pg-docker
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    volumes:
      - /var/db_data/:/var/lib/postgresql/data/
      - ./init_db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    networks:
      - swaplify_network

  app:
    container_name: swaplify-backend
    build: .
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: db
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - swaplify_network

networks:
  swaplify_network:
    driver: bridge
