"""alter tokens table

Revision ID: 094455f92284
Revises: 2c76002ed49b
Create Date: 2021-10-15 23:57:50.719830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '094455f92284'
down_revision = '2c76002ed49b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
