"""alter tokens table

Revision ID: 2c76002ed49b
Revises: 385c4714db56
Create Date: 2021-10-15 23:54:29.523014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c76002ed49b'
down_revision = '385c4714db56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
