"""alter tokens table

Revision ID: 385c4714db56
Revises: 913b1b4b627f
Create Date: 2021-10-15 23:45:15.725618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '385c4714db56'
down_revision = '913b1b4b627f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tokens', ['token'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tokens', type_='unique')
    # ### end Alembic commands ###
