"""Alter tokens table

Revision ID: 9207e0e47c5d
Revises: faabe8113689
Create Date: 2021-10-15 13:00:24.579359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9207e0e47c5d'
down_revision = 'faabe8113689'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('user_ip', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tokens', 'user_ip')
    # ### end Alembic commands ###
