name: Run tests
on: [push]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: 123456
          POSTGRES_DB: swaplify
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
      - uses: actions/checkout@master
#      - name: Create docker netowork
#        run: docker network create --driver=bridge nginx.docker
#      - name: Create postgres volume
#        run: mkdir $HOME/db_data/
#      - name: Up containers
#        run: docker compose up -d --build
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        env:
          DB_USER: postgres
          DB_PASSWORD: 123456
          DB_NAME: swaplify
        run: python -m pytest -v --cov=app
